### ISSUE TITLE
obsidian style wikilinks

### ISSUE THREAD

**Issue by khimaros** [rochacbruno/marmite#115]
i would love to use my obsidian vault with this but it doesn't seem to support the simplified wikilinks syntax `[[another-article]]`. is this feasible to support?

**Comment by rochacbruno** [comment]
AFAIK Comrak (the markdown parser we use) doesn´t support it out of the box,

I think we can add it as a pre-processing step, converting `[[str]]` to `<./str.html>` and then it should just work.


One thing to notice is that Marmite generates a **flat** site, so there will be no subpaths, it is expected that every page is on the same level.

**Comment by rochacbruno** [comment]
#122
