### ISSUE TITLE
Loading config file

### ISSUE THREAD

**Issue by zokaibr** [rochacbruno/marmite#159]
When I run the command to generate the site from example foder, Marmite only searches for the marmite config file if it is specified with the command option `--config`.

I don't know if it is expected, but I think it could be better if Marmite look for file `marmite.yaml` into Input folder by default when the option `--config` is not present.

So, the in order it would be:
1. Check for config file specified at `--config` option
2. Check into Input Folder
3. Load default values

**Comment by rochacbruno** [comment]
Hi @zokaibr 

I currently run

```
cargo run example /tmp/site
```

And it is able to find the `marmite.yaml` on example.

**Comment by zokaibr** [comment]
@rochacbruno I made some tests and yep, I was missing a thing. I was interpreting _INPUT FOLDER_ as the folder with .md files, so I was running the command this way:

```bash
$ marmite --serve example/content example/site
```

But my mistake is: `example/content` does not contain the _marmite.yml_ because it is inside `example`. 😅

I'm closing this issue.
