### ISSUE TITLE
enhancement: Render pages async

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#170]
Here be the dragons 
https://github.com/rochacbruno/marmite/blob/8925fe060bb7979d9df7277ba88eb30e3bf7c034/src/site.rs#L392-L493

that method is called after all content is collected, it will do basically I/O and template rendering, so we need that to run in parallel.

Every call to `render` and `handle` must run async as it is guaranted to not have slug conflicts, it is all rendering + writing to the folder.

**Comment by zokaibr** [comment]
I'm a very beginner in Rust and it's (even more in his concurrency and paralelism world), but I was reading about Rust Mutex and an idea popped up.

Maybe, and just firing a fresh idea, to avoid slug duplications, we can have a Mutex locked data that would be content folder mirror. So, for every page inserted in the folder, it will be mirrored in this Mutex-locked data. I guess this Mutex can be shared with all routines parallel process that will run and be checked and incremented by them.
