### ISSUE TITLE
[feat] Add rebuild functionality to serve mode

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#34]
When serving with `--serve`
I want the server to detect any changes on `input_folder` and regenerate the site.

The http server does not need to reload, but a background thread must be watching for changes and rebuilding the site.

It can be activated with `--watch` and can be used with server or alone.

```
# watch for changes and rebuild
marmite a b --watch

The same, but also starts http server
marmite a b --watch --serve

```

tip: Zola and Cobalt does that, lets inspire on their implementations

**Comment by rochacbruno** [comment]
https://crates.io/crates/hotwatch

**Comment by rochacbruno** [comment]
https://github.com/hanpei/onepage/blob/049509c369a8ba176f719cb3a1c19983d0e58c1f/src/server.rs#L48C3-L115

**Comment by SkySingh04** [comment]
This looks like a fun issue, will be working on it!
