### ISSUE TITLE
[bug] Building the content folder fails

### ISSUE THREAD

**Issue by rdenadai** [rochacbruno/marmite#36]
I was testing and wasn't able to create the content folder from example.

Checking the code I saw that this commit might have introduced a bug: https://github.com/rochacbruno/marmite/commit/0849c7f2b0e51daa31c3894aeb8e8ab5d073e4c3

`content_dir` now contains the full path instead of just the content path ... And in the `Walk` class `input_path` joins `content_dir` again.

```
Path after content_dir: example/content
Path with join: example/example/content
```

**Comment by rochacbruno** [comment]
Fixed on https://github.com/rochacbruno/marmite/commit/560509710a76daa3006ea45c41a9682f360098cb#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR52
