### ISSUE TITLE
[feat] Add syntax highlight

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#4]
This can be done in 2 ways,

Not sure yet which one is the best approach

Important!

- No fancy themes and bloated files, a simple highlight that works on the simple layout is enough
- Must support fenced mermaid and sequence-js blocks

Option 1: https://highlightjs.org/#usage (on the front)

Option 2: https://github.com/trishume/syntect (on SSG)

**Comment by rdenadai** [comment]
I use `highlightjs` on my site ... it works ok, but adds like ~38kb to the site (if you grab the whole package).
You can choose which langs to support and make it small => https://highlightjs.org/download

The image bellow is from my website directly pulling from `cdnjs.cloudflare.com` ...
![image](https://github.com/user-attachments/assets/f942ea48-bf36-4d80-bb24-4ff8505efd01)

Not sure about the `syntect` but probably would be better if it generates less code to be hold by the server.
