### ISSUE TITLE
[feat] Add `--init-templates`  command

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#70]
User has
```bash
.
marmite.yaml
content\
       |_ *.md
```

Then when wanting to start customizing templates, marmite can output the embedded templates

```bash
marmite . site --init-templates
Created `templates` folder
Created `templates/base.html`
...

```
Also `marmite . site --start-theme` would be a command that

- Do what `--init-templates` does
- Create static/ wirh empty files that are referenced on the templates

**Comment by SkySingh04** [comment]
Sounds Fun, Will be working on this!
