### ISSUE TITLE
[feat] Allow customization of display date format

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#82]
The dates shown in `list.html` and `content.html` takes a string format.

That format must be configurable 

`marmite.yaml`
```yaml
output_date_format: "%D/%M/%Y"
```

Check [chrono for valid options](https://docs.rs/chrono/latest/chrono/format/strftime/index.html), invalid date must raise error.

> [!IMPORTANT]
> This has nothing to do with the `input_date_format` on `get_date` function, those are fixed and can't be changed, this issue is only about adding to config and using on templates.

**Comment by brunobarros2093** [comment]
Hi @rochacbruno, how you doing? 
I would like to work on this issue or at least help to solve it, but I am new to Rust, how fast do you want it to be fixed? I may take a while (like a week or two alone)

**Comment by rochacbruno** [comment]
Take your time @brunobarros2093 , I can give you some directions.

- Add `output_date_format` to the `Marmite` struct on `config.rs` along with its default function, the default function will return a String containing `"%b %e, %Y"` which is the default format.

- Then users will be able to add `output_date_format: "other format"` (https://docs.rs/chrono/latest/chrono/format/strftime/index.html)

- Then change templates, wherever there is a `| date(format="...")` replace with `| date(format=site.output_date_format)`

I think that is all.

**Comment by rochacbruno** [comment]
hey @brunobarros2093 there is an open PR for this issue, are you ok if I merge it?

**Comment by brunobarros2093** [comment]
@rochacbruno Sure, no problem, go ahead
