### ISSUE TITLE
[feat] Render 404.html

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/marmite#9]
If content/404.md is found, then it will be rendered normally as a page.

If not found, then a default `404.html` will be copied to the site/ folder.

**Comment by rochacbruno** [comment]
It is important to keep in mind that most people will use github pages, so if this can be covered

https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

**Comment by zokaibr** [comment]
@rochacbruno I'm trying this one : )

But I got stuck on a point related to page generated name.

When Marmite looks to content to generate the .html files based on markdown, it first get the Front Matter slug to generate the html name and if it isn't found, it tries the page title on Front Matter.

So, to avoid having some error on transforming an error page on some other one, I'm thinking on creating a Front Matter item where users can set the error, like this one:
```
---
error: 404
title: Not Found
---
```
Following this format, we can use the `error` item to create the html page (the name would be `404.html` on site root) and redirect to this when and page is not found. With this, user can add a page with any name and any title as long as `error` item is present and it can be used to customize both 404 and 500 errors the application shows today.

**Comment by rochacbruno** [comment]
Hi @zokaibr 

For the case of the static site, 404 is actually the only error page we need, and mainly because Github pages or NGinx allows to specify custom 404 html to render.

I don't think we need to handle any other http status because there is no server processing.

Even redirects, if we ever implement, will be implemented in the `<meta http-equiv="refresh"` approach.

So What I think is that 404.md is really a special case.

Having a `404.md`
```md
![Not Found](https://http.cat/images/404.jpg)
```

Or a `404.html`
```
<img src="https://http.cat/images/404.jpg" />
```

Then on
https://github.com/rochacbruno/marmite/blob/1e89e2ec7dd50545d6cdba089e43317e56573ed4/src/site.rs#L343

We can filter out the special cases from being collected.

and then implement the handling of those special cases on a new function `handle_not_found_page` 

This way we don't need to add more fields to the frontmatter and also we dont need to cleanup 404.html from being listed on the `pages.html` list.

**Comment by zokaibr** [comment]
Got it. Let me try this.
