### ISSUE TITLE
 the enhancement of SEO performance

### ISSUE THREAD

**Issue by lopins** [rochacbruno/marmite#97]
1. List of articles associated with the same tag or TF-IDF 
2. List of popular articles within a period of time.
3. OGP and JSON-LD

---

- [x] Associated content by backlinks
- [x] Associated content by tags
- [x] OGP
- [x] JSON-LD

**Comment by rochacbruno** [comment]
1. You mean listing on the post page, recommend articles based on similar tags? this can be done in the way we did with backlinks.


2.list of popular articles

This would require tracking, I dont want to have builtin tracking so I think this will not be implemented what can be done is to use some JavaScript to fetch this data from the tracking system, I will let it to the user to customize, we can add instructions to the docs.


3. OGP will be added as part of #12

**Comment by rochacbruno** [comment]
- Associated articles by backlinks added
- Popular articles (not going to be added)
- OGP added
- JSONLD missing
